# Generated by Django 4.1.3 on 2022-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kategorien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
